apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sample-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      name: sample-pod
      labels:
        app: sample-app-pod
    spec:
      containers:
        - name: sample-app
          image: dockerhub.io/image    